# Generated by Django 2.2.1 on 2019-05-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_auto_20190508_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodeposition',
            name='node',
        ),
    ]
