# Generated by Django 2.2.1 on 2019-05-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_remove_nodeposition_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='edges',
        ),
        migrations.AddField(
            model_name='graph',
            name='edges',
            field=models.ManyToManyField(related_name='graphs', to='graph.Edge'),
        ),
        migrations.RemoveField(
            model_name='graph',
            name='nodes',
        ),
        migrations.AddField(
            model_name='graph',
            name='nodes',
            field=models.ManyToManyField(related_name='graphs', to='graph.Node'),
        ),
    ]
