# Generated by Django 2.2.1 on 2019-05-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0007_auto_20190509_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph',
            old_name='edge',
            new_name='edges',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='node',
            new_name='nodes',
        ),
        migrations.AlterField(
            model_name='node',
            name='graph',
            field=models.ManyToManyField(related_name='graph_nodes', to='graph.Graph'),
        ),
    ]
