# Generated by Django 2.2.1 on 2019-05-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0008_auto_20190509_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='edges',
        ),
        migrations.AddField(
            model_name='graph',
            name='edges',
            field=models.ManyToManyField(null=True, related_name='graphs', to='graph.Edge'),
        ),
        migrations.RemoveField(
            model_name='graph',
            name='nodes',
        ),
        migrations.AddField(
            model_name='graph',
            name='nodes',
            field=models.ManyToManyField(null=True, related_name='graphs', to='graph.Node'),
        ),
        migrations.AlterField(
            model_name='node',
            name='graph',
            field=models.ManyToManyField(related_name='graphs', to='graph.Graph'),
        ),
    ]
