# Generated by Django 2.2.1 on 2019-05-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0009_auto_20190509_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='edges',
            field=models.ManyToManyField(related_name='graphs', to='graph.Edge'),
        ),
        migrations.AlterField(
            model_name='graph',
            name='nodes',
            field=models.ManyToManyField(related_name='graphs', to='graph.Node'),
        ),
    ]
