# Generated by Django 2.2.1 on 2019-05-09 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0011_auto_20190509_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='graph',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='edges',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='nodes',
        ),
        migrations.RemoveField(
            model_name='node',
            name='position',
        ),
        migrations.AddField(
            model_name='node',
            name='bottom',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='left',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='right',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='top',
            field=models.FloatField(null=True),
        ),
        migrations.RemoveField(
            model_name='node',
            name='graph',
        ),
        migrations.AddField(
            model_name='node',
            name='graph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='graph.Graph'),
        ),
        migrations.DeleteModel(
            name='NodePosition',
        ),
    ]
