# Generated by Django 2.2.1 on 2019-05-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0014_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeTraversal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodes_to_traverse', models.ManyToManyField(related_name='to_travers', to='graph.Node')),
                ('traversed_nodes', models.ManyToManyField(related_name='traversed', to='graph.Node')),
            ],
        ),
        migrations.RemoveField(
            model_name='edge',
            name='graph',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='media'),
        ),
        migrations.DeleteModel(
            name='FindIsland',
        ),
    ]
