# Generated by Django 2.2.1 on 2019-05-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0015_auto_20190512_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='graph',
        ),
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='graph',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
