# Generated by Django 2.2.1 on 2019-05-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0016_auto_20190514_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodetraversal',
            name='connected_nodes',
            field=models.ManyToManyField(related_name='connected', to='graph.Node'),
        ),
    ]
